apiVersion: v1
kind: ConfigMap
metadata:
  name: kubewatch
data:
  .kubewatch.yaml: |
    namespace: ""
    handler:
      discord:
        webhookurl: "<webhookurl>"
    resource:
      deployment: true
      replicationcontroller: false
      replicaset: false
      daemonset: false
      statefulset: false
      services: true
      pod: true
      secret: false
      configmap: false
      hpa: false
      coreevent: false
      event: false
